### ISSUE TITLE
error when install plugin

### ISSUE THREAD

**Issue by Sosha1996** [mrp97/gitbook-plugin-rtl#2]
im very newbie :)
this is my first try to install gitbook.
i try my best to install rtl plugin, but when installing; i get the error message:
`$ npm i gitbook-plugin-rtl`

> /home/sosha/gitbook
> └─┬ gitbook-plugin-rtl@1.0.9 
>   └─┬ cheerio@0.22.0 
>     ├─┬ css-select@1.2.0 
>     │ ├── boolbase@1.0.0 
>     │ ├── css-what@2.1.0 
>     │ ├── domutils@1.5.1 
>     │ └── nth-check@1.0.1 
>     ├─┬ dom-serializer@0.1.0 
>     │ └── domelementtype@1.1.3 
>     ├── entities@1.1.1 
>     ├─┬ htmlparser2@3.9.2 
>     │ ├── domelementtype@1.3.0 
>     │ ├── domhandler@2.4.1 
>     │ ├── inherits@2.0.3 
>     │ └─┬ readable-stream@2.3.6 
>     │   ├── core-util-is@1.0.2 
>     │   ├── isarray@1.0.0 
>     │   ├── process-nextick-args@2.0.0 
>     │   ├── safe-buffer@5.1.1 
>     │   ├── string_decoder@1.1.1 
>     │   └── util-deprecate@1.0.2 
>     ├── lodash.assignin@4.2.0 
>     ├── lodash.bind@4.2.1 
>     ├── lodash.defaults@4.2.0 
>     ├── lodash.filter@4.6.0 
>     ├── lodash.flatten@4.4.0 
>     ├── lodash.foreach@4.5.0 
>     ├── lodash.map@4.6.0 
>     ├── lodash.merge@4.6.1 
>     ├── lodash.pick@4.4.0 
>     ├── lodash.reduce@4.6.0 
>     ├── lodash.reject@4.6.0 
>     └── lodash.some@4.6.0 
> 
> npm WARN enoent ENOENT: no such file or directory, open '/home/sosha/gitbook/package.json'
> npm WARN gitbook No description
> npm WARN gitbook No repository field.
> npm WARN gitbook No README data
> npm WARN gitbook No license field.

i use ubuntu 18.04.

please help me...

**Comment by mrp97** [comment]
@Sosha1996 You need to create package.json file for your book, enter below command in your book directory in terminal:

`npm init`

**Comment by Sosha1996** [comment]
very thanks, this is very helpful... <3
