### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by omidonrails** [mrp97/gitbook-plugin-rtl#3]
سلام
چطوری نصب و استفاده کنم خواهشا راهنما ارايه میدید

**Comment by mrp97** [comment]
سلام. 
قبل از هر چیز دقت کنید که این پلاگین برای ورژن ۳ گیت‌بوک کار میکنه و ورژن ۴ گیت‌بوک کاملا عوض شده. راهنمای استفاده رو به توضیحات همین ریپو اضافه کردم. 

با تشکر از شما

**Comment by omidonrails** [comment]
> سلام.
> قبل از هر چیز دقت کنید که این پلاگین برای ورژن ۳ گیت‌بوک کار میکنه و ورژن ۴ گیت‌بوک کاملا عوض شده. راهنمای استفاده رو به توضیحات همین ریپو اضافه کردم.
> 
> با تشکر از شما

برای ورژن ۴ میخوام. اخرین ورژن. البته من دیدم که خودش گزینه راست به چپ داره به هرحال ممنون
